"""Maiambiente (Maia, Portugal) - reading the yearly collection calendar.

No login and no OCR. The public lookup resolves street -> house number ->
collection circuit -> yearly PDF, and the body of that PDF is read
geometrically: the month block, weekday row and week column give the date, the
fill colour gives the waste stream.

GENERATED by tools/build_wcs.py from custom_components/maiambiente/lib/ in
https://github.com/CargoTechSolutions/ha-maiambiente - do not edit by hand,
edit the library and regenerate.
"""

import datetime as dt
import io
import re
import ssl
import struct
import time
import zlib
from collections import Counter

from PIL import Image, ImageChops

# ------------------------------ const.py
VERSION = "1.0.1"

# exact RGB values read off the calendar's own legend
PALETTE = {
    "vidro": (91, 160, 50),
    "embalagens": (252, 186, 8),
    "papel": (15, 128, 195),
    "alimentares": (147, 89, 84),
    "jardim": (171, 210, 155),
    "indiferenciados": (178, 178, 178),
    "sem_recolha": (227, 5, 19),
}

LABELS = {
    "vidro": "Vidro",
    "embalagens": "Embalagens de plástico e metal",
    "papel": "Papel e cartão",
    "alimentares": "Resíduos alimentares",
    "jardim": "Resíduos de jardim",
    "indiferenciados": "Resíduos indiferenciados",
    "sem_recolha": "Não haverá recolha",
}

# streams that are actual collections (sem_recolha is an exception marker)
FLUXOS = [f for f in LABELS if f != "sem_recolha"]

# fallback MDI icon, for when the bin images are not used
MDI = {
    "vidro": "mdi:bottle-wine-outline",
    "embalagens": "mdi:recycle-variant",
    "papel": "mdi:newspaper-variant-outline",
    "alimentares": "mdi:food-apple-outline",
    "jardim": "mdi:leaf",
    "indiferenciados": "mdi:trash-can-outline",
    "sem_recolha": "mdi:calendar-remove-outline",
}

TEAL = (4, 94, 99)  # dark green of the month bars (the grid anchor)
TOL = 30  # maximum L1 distance to a palette colour
THROTTLE = 1.5  # seconds between requests (the server 403s on bursts)
BASE = "https://servicos.maiambiente.pt/cal{year}"
UA = (
    f"Mozilla/5.0 (compatible; ha-maiambiente/{VERSION}; "
    "+https://github.com/CargoTechSolutions/ha-maiambiente)"
)


# ------------------------------ tls.py
# GlobalSign GCC R6 AlphaSSL CA 2025
#   issuer:      OU = GlobalSign Root CA - R6, O = GlobalSign, CN = GlobalSign
#   valid:       2025-05-21 .. 2027-05-21
#   sha256:      A8:83:55:92:31:F8:38:8D:AF:35:CE:41:C8:10:10:40:
#                AE:8F:D9:B6:56:43:42:47:B9:47:5A:F5:92:CC:08:CA
#   source:      http://secure.globalsign.com/cacert/gsgccr6alphasslca2025.crt
INTERMEDIATE_PEM = """\
-----BEGIN CERTIFICATE-----
MIIFjTCCA3WgAwIBAgIRAIN9TriekS/nLK07x2kt3CAwDQYJKoZIhvcNAQELBQAw
TDEgMB4GA1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjYxEzARBgNVBAoTCkds
b2JhbFNpZ24xEzARBgNVBAMTCkdsb2JhbFNpZ24wHhcNMjUwNTIxMDIzNjUyWhcN
MjcwNTIxMDAwMDAwWjBVMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2ln
biBudi1zYTErMCkGA1UEAxMiR2xvYmFsU2lnbiBHQ0MgUjYgQWxwaGFTU0wgQ0Eg
MjAyNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ/oiu0Bviq52UUE
ADbFWmgu3rC7KDSMoorLN1Wd03McG3Z1aP71DlPCE33838r72Dfuj5M9LXfiQLJp
Au6MwNExmKOzothw4x0zGf5oBYyrCMGm3fBpLPafwYQ3MchBOWMTbf83rKUPLH48
KCJ0MnU8GUl8oA/J81wIvbbKPuNrFf6hvJDccjzc4NyxLz3A89zjV2g5whCg5O0u
9YX4Zxk9JHuc/LvllOJO4waAYLjbWBJkz3rV3ts1SmSYnJqmyRTIjXwQgRvhEYqt
DbRskt0W7M6cPwCze3GTBN2UHNpHkMs3YmVxku68I0aOQn5+uz//fDROP3z1Z/7I
APteRtECAwEAAaOCAV8wggFbMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU
xbSTj28r3B5Iv7cQMIXO0bK7SC0wHwYDVR0jBBgwFoAUrmwFo5MT4qLn4tcc1sfw
f8hnU6AwewYIKwYBBQUHAQEEbzBtMC4GCCsGAQUFBzABhiJodHRwOi8vb2NzcDIu
Z2xvYmFsc2lnbi5jb20vcm9vdHI2MDsGCCsGAQUFBzAChi9odHRwOi8vc2VjdXJl
Lmdsb2JhbHNpZ24uY29tL2NhY2VydC9yb290LXI2LmNydDA2BgNVHR8ELzAtMCug
KaAnhiVodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29tL3Jvb3QtcjYuY3JsMCEGA1Ud
IAQaMBgwCAYGZ4EMAQIBMAwGCisGAQQBoDIKAQMwDQYJKoZIhvcNAQELBQADggIB
AB/uvBuZf4CiuSahwiXn4geF52roAH+6jxsEPTXTfb7bbeMDXsYgRRsOTNA70ruZ
Tnz5DfFMuBhNoFhIFb0qR1izdy6VkdKOqFPNF2dOFI1EcnY9l2ory9mrzHqVbrL4
vzUd17FLUVyjTVU7PAv4nxyhnO1GTeT83YlrdRF31NyR6bvZVTEERHmpbWSgeveJ
LRtaMzlGWiLZ8IwkH7o6GH3jp/KPtDW4Npu8w64HrRZdN2pqQhi7+YKwfHM7H+2U
dM1BGN0sjOWMVbMSB9MtCsleS2Mb7TRZEbOHxECJLLIluQypZr7Pol3+hAqrhyKI
k+6y+Da0NeDuWxW59Ku4NvClqW1UFX1SpfNGhzVfp/CH+vPM1tySomx2jE0EnYZu
GwVucXPBsp5nUWqUV9+143glVuS7GTg9hFPjNBInn17HbCoIIQIOzj5Vd9bK3A9U
GxXNpwenDHEalCsD/4eQYDHPhFE7sNe0D/OXu+FAM02VZkARx37Jp4bDdujvgL9P
vZPR3wThvDN1CTU8Bc3xea3yKFAraKcPZLkhReQUAm2VpR+HSJRPlUpYizlF9WkL
h3KcAVCBJWvnOkVwxyU5QJMcnwW95JlOtx+9100GL99jHE5rs3gXp7F4bg8H01QT
9jVOhBBmQ7nQoXuwI0tqal2QUqZz3eeu62CU7xBwtfYR
-----END CERTIFICATE-----
"""

# What to tell the user when even the pinned intermediate no longer helps.
CHAIN_HINT = (
    "TLS verification against servicos.maiambiente.pt failed. Their server "
    "sends an incomplete certificate chain and the intermediate pinned in "
    "lib/tls.py no longer bridges it — it most likely needs refreshing. See "
    "the docstring of that module for how."
)


def tls_context() -> ssl.SSLContext:
    """Default verification, plus the intermediate the server forgets to send."""
    ctx = ssl.create_default_context()
    ctx.load_verify_locations(cadata=INTERMEDIATE_PEM)
    return ctx


def tls_session():
    """A `requests.Session` using :func:`tls_context`, or None without requests."""
    try:
        import requests
        import urllib3
    except ImportError:  # pragma: no cover - urllib fallback path
        return None

    class _Adapter(requests.adapters.HTTPAdapter):
        """Transport adapter that carries our SSL context."""

        def __init__(self, ssl_context, **kwargs):
            self._ssl_context = ssl_context
            super().__init__(**kwargs)

        def init_poolmanager(self, connections, maxsize, block=False, **kwargs):
            self.poolmanager = urllib3.poolmanager.PoolManager(
                num_pools=connections,
                maxsize=maxsize,
                block=block,
                ssl_context=self._ssl_context,
                **kwargs,
            )

    sess = requests.Session()
    sess.mount("https://", _Adapter(tls_context()))
    return sess


# ------------------------------ consulta.py
class MaiambienteError(Exception):
    """Something went wrong talking to Maiambiente."""


class Cliente:
    """Throttled session. Uses requests when available, urllib otherwise."""

    def __init__(self, year, throttle=THROTTLE, timeout=60):
        self.year = year
        self.throttle = throttle
        self.timeout = timeout
        self._last = 0.0
        self._sess = tls_session()

    # ------------------------------------------------------------------ HTTP
    def _wait(self):
        delta = time.monotonic() - self._last
        if delta < self.throttle:
            time.sleep(self.throttle - delta)
        self._last = time.monotonic()

    def _request(self, url, data=None, params=None):
        self._wait()
        if self._sess is not None:
            import requests

            try:
                response = (
                    self._sess.post(url, data=data, timeout=self.timeout)
                    if data
                    else self._sess.get(url, params=params, timeout=self.timeout)
                )
            except requests.exceptions.SSLError as err:
                raise MaiambienteError(CHAIN_HINT) from err
            if response.status_code == 403:
                raise MaiambienteError(
                    "403 from the server - too many requests in a row; "
                    "raise the throttle"
                )
            response.raise_for_status()
            return response.content, response.headers.get("content-type", "")

        # fallback without requests
        import ssl
        import urllib.parse
        import urllib.request

        if params:
            url = url + "?" + urllib.parse.urlencode(params)
        body = urllib.parse.urlencode(data).encode() if data else None
        request = urllib.request.Request(url, data=body, headers={"User-Agent": UA})
        try:
            with urllib.request.urlopen(
                request, timeout=self.timeout, context=tls_context()
            ) as response:
                return response.read(), response.headers.get("content-type", "")
        except ssl.SSLCertVerificationError as err:
            raise MaiambienteError(CHAIN_HINT) from err

    def _ajax(self, data):
        raw, _ = self._request(
            BASE.format(year=self.year) + "/ajax_refresh.php", data=data
        )
        return raw.decode("utf-8", "replace")

    # ------------------------------------------------------------------- API
    def arruamentos(self, keyword):
        """Streets whose name contains `keyword` (without "de"/"da"/"das")."""
        html = self._ajax(
            {
                "keyword": keyword,
                "type": f"arruamento{self.year}",
                "freguesia": "",
                "tipoarruamento": "",
            }
        )
        return [m.group(1) for m in re.finditer(r"set_item\d*\([^)]*'([^']*)'\)", html)]

    def numeros(self, arruamento):
        """House numbers of the street, each with its own idcal/idunico."""
        html = self._ajax(
            {
                "keyword": arruamento,
                "type": f"numeropolicia{self.year}",
                "freguesia": "",
                "tipoarruamento": "",
            }
        )
        out = []
        for m in re.finditer(r'href="([^"]*)"[^>]*>([^<]*)<', html):
            qs = dict(re.findall(r"([^?=&]+)=([^&]*)", m.group(1)))
            if not qs.get("idcal"):
                continue
            out.append(
                {
                    "numero": m.group(2).strip(),
                    "idcal": qs["idcal"],
                    "idunico": qs.get("idunico", ""),
                }
            )
        return out

    def circuitos(self, arruamento, numero):
        """Circuit codes of the address (A=food waste, E=packaging, ...)."""
        html = self._ajax(
            {
                "keyword": arruamento,
                "type": "circuito",
                "numeropolicia": numero,
                "freguesia": "",
                "tipoarruamento": "",
            }
        )
        m = re.search(r"set_circuito\('([^']*)'", html)
        return [c.strip() for c in m.group(1).split(",")] if m else []

    def pdf(self, idcal, idunico, arruamento, numero):
        """The address's yearly calendar PDF."""
        raw, ctype = self._request(
            BASE.format(year=self.year) + f"/cal{self.year}.php",
            params={
                "idcal": idcal,
                "idunico": idunico,
                "type": f"logcircuito{self.year}",
                "morada": arruamento,
                "numeropolicia": numero,
            },
        )
        if "pdf" not in ctype:
            raise MaiambienteError(f"the response is not a PDF ({ctype})")
        return raw


# --------------------------------------------------------------- convenience
def procurar_arruamento(keyword, year, cliente=None):
    return (cliente or Cliente(year)).arruamentos(keyword)


def procurar_numeros(arruamento, year, cliente=None):
    return (cliente or Cliente(year)).numeros(arruamento)


def obter_circuitos(arruamento, numero, year, cliente=None):
    return (cliente or Cliente(year)).circuitos(arruamento, numero)


def descarregar_pdf(idcal, idunico, arruamento, numero, year, cliente=None):
    return (cliente or Cliente(year)).pdf(idcal, idunico, arruamento, numero)


# ------------------------------ calendario.py
# month blocks in the image: 3 rows x 4 columns, rightmost group = Jan/Feb/Mar
MONTH_GRID = [[10, 7, 4, 1], [11, 8, 5, 2], [12, 9, 6, 3]]

_IMG_RE = re.compile(rb"/Subtype\s*/Image(?:.{0,600}?)>>\s*stream\r?\n", re.S)

# colour -> stream memo, filled on demand by classificar()
_COLOUR_CACHE: dict = {}


class CalendarioError(Exception):
    """The PDF is not in the expected shape."""


# ------------------------------------------------------------- PDF -> images
def _chunk(tag, data):
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def _wrap_png(idat, w, h):
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)  # 8 bpc, type 2 = RGB
    return (
        b"\x89PNG\r\n\x1a\n"
        + _chunk(b"IHDR", ihdr)
        + _chunk(b"IDAT", idat)
        + _chunk(b"IEND", b"")
    )


def imagens_do_pdf(pdf_bytes):
    """RGB images in the PDF (only /FlateDecode + /Predictor 15 + DeviceRGB)."""
    for m in _IMG_RE.finditer(pdf_bytes):
        # keep the dictionary scan inside THIS object: picking up the previous
        # object's /Length truncates the stream and the image comes out corrupt
        ini = pdf_bytes.rfind(b" obj", 0, m.start())
        head = pdf_bytes[ini if ini >= 0 else max(0, m.start() - 600) : m.end()]

        def val(key, default=None, head=head):
            g = re.search(rf"/{key}\s+(\d+)".encode(), head)
            return int(g.group(1)) if g else default

        w, h = val("Width"), val("Height")
        if not w or not h or val("BitsPerComponent", 8) != 8:
            continue
        if (
            b"/FlateDecode" not in head
            or b"/DeviceRGB" not in head
            or re.search(rb"/Predictor\s+15", head) is None
        ):
            continue
        length = val("Length")
        if length:
            raw = pdf_bytes[m.end() : m.end() + length]
        else:
            raw = pdf_bytes[m.end() : pdf_bytes.find(b"endstream", m.end())]
        try:
            img = Image.open(io.BytesIO(_wrap_png(raw, w, h)))
            # the PNG we just built is colour type 2, so it decodes straight to
            # RGB. Calling convert("RGB") anyway would hand back a full copy of
            # a 25 megapixel image, which on a 2 GB Home Assistant box is the
            # difference between working and being OOM-killed.
            yield img if img.mode == "RGB" else img.convert("RGB")
        except Exception:
            continue


def texto_do_pdf(pdf_bytes):
    """Text of the content streams - enough for the PNG name and the circuits."""
    out = []
    for m in re.finditer(rb"stream\r?\n", pdf_bytes):
        fim = pdf_bytes.find(b"endstream", m.end())
        try:
            data = zlib.decompress(pdf_bytes[m.end() : fim])
        except Exception:
            continue
        if b"Tj" not in data and b"TJ" not in data:
            continue
        for t in re.finditer(rb"\((?:\\.|[^\\()])*\)", data):
            s = re.sub(rb"\\([()\\])", rb"\1", t.group(0)[1:-1])
            out.append(s.decode("latin-1"))
    return "\n".join(out)


def assinatura(pdf_bytes):
    """Identify the calendar.

    `png` is the name of the embedded bitmap (e.g. 20502edbd9f2_2026.png).
    Because the calendar belongs to the circuit, that name works as a cache
    key: if it has not changed, neither has the calendar.
    """
    txt = texto_do_pdf(pdf_bytes)
    png = re.search(r"([0-9a-f]{6,}_\d{4}\.png)", txt)
    circ = re.findall(r"[A-Z]{1,2}\d+\.\d+_\d{4}", txt)
    morada = re.search(r"^(.+?,\s*\d.*)$", txt, re.M)
    return {
        "png": png.group(1) if png else None,
        "circuitos": sorted(set(circ)) or None,
        "morada": morada.group(1).strip() if morada else None,
    }


# ------------------------------------------------------------ reading the grid
def classificar(cor):
    """Name of the stream whose colour is within TOL (L1 distance), or None."""
    v = _COLOUR_CACHE.get(cor)
    if v is None:
        melhor, d = None, TOL
        for nome, c in PALETTE.items():
            dd = abs(cor[0] - c[0]) + abs(cor[1] - c[1]) + abs(cor[2] - c[2])
            if dd < d:
                melhor, d = nome, dd
        v = _COLOUR_CACHE[cor] = melhor
    return v


def _mascara(im):
    """An 'L' image at 255 wherever the pixel is a palette colour."""
    w, h = im.size
    acc = Image.new("L", (w, h), 0)
    for c in PALETTE.values():
        r, g, b = ImageChops.difference(im, Image.new("RGB", (w, h), c)).split()
        s = ImageChops.add(ImageChops.add(r, g), b)  # L1, saturates at 255
        acc = ImageChops.lighter(acc, s.point(lambda v: 255 if v < TOL else 0))
    return acc


def _componentes(mask, margem_esq):
    """Connected components, by byte runs (regex in C) + union-find."""
    w, h = mask.size
    data = mask.tobytes()
    pai = [0]

    def raiz(x):
        while pai[x] != x:
            pai[x] = pai[pai[x]]
            x = pai[x]
        return x

    def unir(a, b):
        ra, rb = raiz(a), raiz(b)
        if ra != rb:
            pai[max(ra, rb)] = min(ra, rb)

    corrida = re.compile(b"\xff+")
    ant, caixas = [], {}
    for y in range(h):
        linha = data[y * w : (y + 1) * w]
        atual = []
        for m in corrida.finditer(linha, margem_esq):
            x0, x1 = m.start(), m.end() - 1
            lbl = None
            for px0, px1, plbl in ant:
                if px1 < x0:
                    continue
                if px0 > x1:
                    break
                if lbl is None:
                    lbl = plbl
                else:
                    unir(lbl, plbl)
            if lbl is None:
                lbl = len(pai)
                pai.append(lbl)
            atual.append((x0, x1, lbl))
            cx = caixas.get(lbl)
            if cx is None:
                caixas[lbl] = [x0, y, x1, y]
            else:
                cx[0] = min(cx[0], x0)
                cx[2] = max(cx[2], x1)
                cx[3] = y
        ant = atual

    final = {}
    for lbl, (x0, y0, x1, y1) in caixas.items():
        r = raiz(lbl)
        f = final.get(r)
        if f is None:
            final[r] = [x0, y0, x1, y1]
        else:
            f[0] = min(f[0], x0)
            f[1] = min(f[1], y0)
            f[2] = max(f[2], x1)
            f[3] = max(f[3], y1)
    return list(final.values())


def _agrupar(vals, tol):
    vals = sorted(vals)
    g = [[vals[0]]]
    for v in vals[1:]:
        if v - g[-1][-1] <= tol:
            g[-1].append(v)
        else:
            g.append([v])
    return [sum(x) / len(x) for x in g]


def _mediana(v):
    v = sorted(v)
    return v[len(v) // 2]


def _barras_dos_meses(im):
    """Bounding boxes of the 12 dark-green bars carrying the month names.

    They anchor the grid: they say which band (block row) and which group
    (block column) each month sits in, without depending on circles being
    present. That keeps the alignment intact for circuits that do not collect
    on some weekday.
    """
    w, h = im.size
    r, g, b = ImageChops.difference(im, Image.new("RGB", (w, h), TEAL)).split()
    mask = ImageChops.add(ImageChops.add(r, g), b).point(lambda v: 255 if v < 40 else 0)
    barras = []
    for x0, y0, x1, y1 in _componentes(mask, 0):
        bw, bh = x1 - x0 + 1, y1 - y0 + 1
        if bh < h * 0.2 or bh > h * 0.45 or bw > bh * 0.25 or bw < 15:
            continue
        barras.append((x0, y0, x1, y1))
    if len(barras) != 12:
        raise CalendarioError(f"expected 12 month bars, found {len(barras)}")
    bandas = sorted({b[1] for b in barras})
    grupos = sorted({b[0] for b in barras})
    bandas = _agrupar(bandas, 40)
    grupos = _agrupar(grupos, 40)
    if len(bandas) != 3 or len(grupos) != 4:
        raise CalendarioError(
            f"month bars in {len(bandas)} bands x {len(grupos)} groups"
        )
    out = {}
    for x0, y0, x1, y1 in barras:
        br = min(range(3), key=lambda i: abs(bandas[i] - y0))
        bc = min(range(4), key=lambda i: abs(grupos[i] - x0))
        out[(br, bc)] = (x0, y0, x1, y1)
    if len(out) != 12:
        raise CalendarioError("overlapping month bars")
    return out


def _encaixar(valor, candidatos, tol):
    """Snap `valor` to the nearest candidate, if it is closer than `tol`."""
    if not candidatos:
        return valor
    melhor = min(candidatos, key=lambda c: abs(c - valor))
    return melhor if abs(melhor - valor) <= tol else valor


def ler_calendario(pdf_bytes, year):
    """Return ({datetime.date: [streams]}, [warnings]).

    Raises CalendarioError when the grid stops being recognisable - the signal
    that Maiambiente has changed the calendar's design.
    """
    im, melhor = None, -1
    for cand in imagens_do_pdf(pdf_bytes):
        # score on a subsample: the fill colours are flat, so nearest-neighbour
        # keeps them exact, and this avoids walking 25 million pixels per
        # candidate just to decide which image is the calendar
        amostra_im = cand.resize(
            (cand.width // 8 or 1, cand.height // 8 or 1), Image.NEAREST
        )
        cores = amostra_im.getcolors(1 << 16) or []
        score = sum(n for n, c in cores if classificar(c))
        del amostra_im, cores
        if score > melhor:
            im, melhor = cand, score
        else:
            del cand
    if im is None:
        raise CalendarioError("could not find the calendar image in the PDF")

    w, h = im.size
    margem = int(w * 0.05)  # the legend column, on the left
    circulos = []
    for x0, y0, x1, y1 in _componentes(_mascara(im), margem):
        ww, hh = x1 - x0 + 1, y1 - y0 + 1
        if ww < 25 or hh < 25 or abs(ww - hh) > 10:
            continue
        circulos.append(((x0 + x1) / 2.0, (y0 + y1) / 2.0))
    if len(circulos) < 100:
        raise CalendarioError(
            f"only detected {len(circulos)} circles - has the format changed?"
        )

    barras = _barras_dos_meses(im)
    altura_barra = _mediana([b[3] - b[1] + 1 for b in barras.values()])
    # the bar spans 7 day rows with an equal margin above and below
    passo_barra = altura_barra * 0.1435

    linhas = _agrupar([c[1] for c in circulos], 15)
    colunas = _agrupar([c[0] for c in circulos], 15)

    def passo(vals, referencia):
        difs = [
            d
            for d in (vals[i + 1] - vals[i] for i in range(len(vals) - 1))
            if referencia * 0.85 < d < referencia * 1.15
        ]
        return _mediana(difs) if difs else referencia

    row_pitch = passo(linhas, passo_barra)
    col_pitch = passo(colunas, passo_barra)

    rad = int(col_pitch * 0.30)  # square inscribed in the circle
    area = (2 * rad + 1) ** 2

    def amostra(cx, cy):
        """Streams present in the cell (each with >=15% of the pixels), or []."""
        if not (rad <= cx < w - rad and rad <= cy < h - rad):
            return []
        cnt = Counter()
        for n, cor in (
            im.crop((cx - rad, cy - rad, cx + rad + 1, cy + rad + 1)).getcolors(1 << 16)
            or []
        ):
            f = classificar(cor)
            if f:
                cnt[f] += n
        tot = sum(cnt.values())
        if tot < area * 0.25:  # blank cell: no collection
            return []
        return [k for k, v in cnt.most_common() if v / tot >= 0.15]

    eventos, avisos = {}, []
    for (br, bc), (bx0, by0, _bx1, by1) in sorted(barras.items()):
        month = MONTH_GRID[br][bc]
        # row 0 (Monday) and week column 0, anchored on the month bar and then
        # snapped onto the circles that actually exist
        y_seg = _encaixar(
            by0 + ((by1 - by0 + 1) - 6 * row_pitch) / 2.0, linhas, row_pitch * 0.4
        )
        x_sem0 = _encaixar(bx0 - col_pitch, colunas, col_pitch * 0.4)

        primeiro = dt.date(year, month, 1)
        segunda = primeiro - dt.timedelta(days=primeiro.weekday())
        for row in range(7):  # Mon..Sun
            cy = round(y_seg + row * row_pitch)
            for semana in range(6):  # at most 6 weeks
                fluxos = amostra(round(x_sem0 - semana * col_pitch), cy)
                if not fluxos:
                    continue
                d = segunda + dt.timedelta(days=7 * semana + row)
                if d not in eventos or len(fluxos) > len(eventos[d]):
                    eventos[d] = fluxos
    if not eventos:
        raise CalendarioError("extracted no collection at all from the calendar")
    return eventos, avisos


# -------------------------------------------------------------------- export
def para_ics(eventos, nome="Recolha de resíduos (Maiambiente)", hora="14:00"):
    """iCalendar with one event per stream per day."""
    hh, mm = (int(x) for x in hora.split(":"))
    agora = dt.datetime.now(dt.timezone.utc)
    linhas = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//ha-maiambiente//PT",
        "CALSCALE:GREGORIAN",
        f"X-WR-CALNAME:{nome}",
        "X-WR-TIMEZONE:Europe/Lisbon",
    ]
    for d in sorted(eventos):
        for f in eventos[d]:
            cab = [
                "BEGIN:VEVENT",
                f"UID:{d:%Y%m%d}-{f}@maiambiente",
                f"DTSTAMP:{agora:%Y%m%dT%H%M%SZ}",
            ]
            if f == "sem_recolha":
                linhas += [
                    *cab,
                    f"DTSTART;VALUE=DATE:{d:%Y%m%d}",
                    f"DTEND;VALUE=DATE:{d + dt.timedelta(days=1):%Y%m%d}",
                    f"SUMMARY:{LABELS[f]}",
                    "END:VEVENT",
                ]
            else:
                s = dt.datetime.combine(d, dt.time(hh, mm))
                linhas += [
                    *cab,
                    f"DTSTART;TZID=Europe/Lisbon:{s:%Y%m%dT%H%M%S}",
                    f"DTEND;TZID=Europe/Lisbon:{s + dt.timedelta(hours=1):%Y%m%dT%H%M%S}",
                    f"SUMMARY:{LABELS[f]}",
                    f"CATEGORIES:{f}",
                    "END:VEVENT",
                ]
    linhas.append("END:VCALENDAR")
    return "\r\n".join(linhas) + "\r\n"
