blank_issues_enabled: false
contact_links:
  - name: Question / Help
    about: Ask the community a question or get help with setup
    url: https://github.com/mampfes/hacs_waste_collection_schedule/discussions/categories/q-a
