waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: His
        mm_frm_str_sel: <my_street>
      customize:
        - type: brown bin
          show: no
        - type: green bin
          alias: Yard Waste
        - type: black bin
          alias: Garbage

  sensors:
    # next collection
    - name: next_collection

    # next yard waste collection
    - name: next_yard_collection
      types:
        - Yard Waste

    # next garbage collection
    - name: next_garbage_collection
      types:
        - Garbage
