import logging
from datetime import date

import requests
from bs4 import BeautifulSoup
from waste_collection_schedule import Collection  # type: ignore[attr-defined]
from waste_collection_schedule.exceptions import SourceArgumentNotFoundWithSuggestions
from waste_collection_schedule.service.ICS import ICS

TITLE = "AWB Oldenburg"
DESCRIPTION = "Source for 'Abfallwirtschaftsbetrieb Stadt Oldenburg (Oldb)'."
URL = "https://www.oldenburg.de"
TEST_CASES = {
    "Polizeiinspektion Oldenburg": {"street": "Friedhofsweg", "house_number": 30}
}

BASE_URL = "https://www.oldenburg.de"
API_URL = (
    BASE_URL
    + "/startseite/stadtraum/umwelt/abfall-entsorgung/awb-von-a-bis-z/abfuhrkalender.html"
)

_LOGGER = logging.getLogger(__name__)

PARAM_TRANSLATIONS = {
    "de": {
        "street": "Straße",
        "house_number": "Hausnummer",
    }
}


class Source:
    def __init__(self, street, house_number):
        self._street = street
        self._house_number = house_number
        self._ics = ICS(regex=r"(.*)\:\s*\!")

    def fetch(self):
        s = requests.Session()
        r = s.get(API_URL)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")

        # Calendar form is the second form on the page
        form = soup.find_all("form")[1]

        # Build street mapping from the street <select> element
        street_select = form.find(
            "select",
            {"name": "tx_collectioncalendar_collectioncalendar[street]"},
        )
        mapping = {
            opt.text.strip(): opt["value"]
            for opt in street_select.find_all("option")
            if opt.get("value")
        }

        if self._street not in mapping:
            raise SourceArgumentNotFoundWithSuggestions(
                "street", self._street, list(mapping.keys())
            )
        street_idx = mapping[self._street]

        # Collect TYPO3 security tokens from hidden inputs
        data = {
            inp["name"]: inp.get("value", "")
            for inp in form.find_all("input", {"name": True})
        }

        data["tx_collectioncalendar_collectioncalendar[year]"] = str(date.today().year)
        data["tx_collectioncalendar_collectioncalendar[wasteTypes][1]"] = "1"
        data["tx_collectioncalendar_collectioncalendar[wasteTypes][2]"] = "2"
        data["tx_collectioncalendar_collectioncalendar[wasteTypes][3]"] = "3"
        data["tx_collectioncalendar_collectioncalendar[wasteTypes][4]"] = "4"
        data["tx_collectioncalendar_collectioncalendar[wasteTypes][5]"] = "5"
        data["tx_collectioncalendar_collectioncalendar[street]"] = street_idx
        data["tx_collectioncalendar_collectioncalendar[houseNumber]"] = str(
            self._house_number
        )
        data["tx_collectioncalendar_collectioncalendar[privacyPolicy-checkbox]"] = "1"

        action = form.get("action", "")
        post_url = BASE_URL + action if action.startswith("/") else action

        r2 = s.post(post_url, data=data)
        r2.raise_for_status()
        soup2 = BeautifulSoup(r2.text, "html.parser")

        # Find the ICS export link generated by the server (includes cHash)
        ics_link = None
        for a in soup2.find_all("a", href=True):
            if "exportIcs" in a["href"]:
                href = a["href"]
                ics_link = BASE_URL + href if href.startswith("/") else href
                break

        if not ics_link:
            raise Exception("ICS export link not found. Check street and house number.")

        r3 = s.get(ics_link)
        r3.raise_for_status()

        entries = []
        for d in self._ics.convert(r3.text):
            entries.append(Collection(d[0], d[1]))
        return entries
