import re

import requests
from bs4 import BeautifulSoup
from waste_collection_schedule import Collection, Icons  # type: ignore[attr-defined]
from waste_collection_schedule.exceptions import SourceArgumentNotFoundWithSuggestions
from waste_collection_schedule.service.ICS import ICS

TITLE = "Gemeinde Hasselroth"
DESCRIPTION = "Source for Gemeinde Hasselroth, Hesse, Germany waste collection."
URL = "https://www.hasselroth.de"
COUNTRY = "de"
TEST_CASES = {
    "Neuenhasslau": {"district": "Neuenhasslau"},
    "Niedermittlau": {"district": "Niedermittlau"},
    "Gondsroth": {"district": "Gondsroth"},
}

ICON_MAP = {
    "altpapier": Icons.PAPER,
    "biomüll": Icons.BIO_KITCHEN,
    "gelbe": Icons.RECYCLING,
    "restmüll": Icons.GENERAL_WASTE,
    "sperrmüll": Icons.BULKY,
    "sperr.": Icons.BULKY,
    "weihnachtsbäume": Icons.CHRISTMAS_TREE,
}

PAGE_URL = "https://www.hasselroth.de/buergerportal/rathaus/abfallentsorgung/ics/"

PARAM_TRANSLATIONS = {
    "de": {
        "district": "Ortsteil",
    },
}
PARAM_DESCRIPTIONS = {
    "en": {
        "district": "The Hasselroth district (Ortsteil), e.g. 'Neuenhasslau', "
        "'Niedermittlau' or 'Gondsroth'",
    },
    "de": {
        "district": "Der Hasselrother Ortsteil, z. B. 'Neuenhasslau', "
        "'Niedermittlau' oder 'Gondsroth'",
    },
}

# Matches link labels like "Download: Kalender 2026 Neuenhasslau.ics"
CALENDAR_LINK_PATTERN = re.compile(r"Kalender\s+\d{4}\s+([^.]+)\.ics", re.IGNORECASE)


class Source:
    def __init__(self, district: str):
        self._district: str = district.strip().lower()
        self._ics = ICS()

    def fetch(self) -> list[Collection]:
        r = requests.get(PAGE_URL)
        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")

        # The list of downloadable ICS files (one per district/Ortsteil and
        # year) is regenerated by the municipality every year, including a
        # fresh access token in the query string, so we always have to
        # discover the current download links instead of hardcoding them.
        district_links: dict[str, list[str]] = {}
        for a in soup.find_all("a", href=True):
            href = a["href"]
            if ".ics" not in href.lower():
                continue
            label = a.get("title") or a.get_text() or href
            match = CALENDAR_LINK_PATTERN.search(label)
            if not match:
                continue
            district_name = match.group(1).strip().lower()
            district_links.setdefault(district_name, []).append(href)

        if self._district not in district_links:
            raise SourceArgumentNotFoundWithSuggestions(
                "district", self._district, list(district_links.keys())
            )

        entries = []
        for href in district_links[self._district]:
            r = requests.get(href)
            r.raise_for_status()
            r.encoding = "utf-8"  # requests doesn't guess the encoding correctly
            for date, summary in self._ics.convert(r.text):
                icon = ICON_MAP.get(summary.split(" ")[0].lower())
                entries.append(Collection(date=date, t=summary, icon=icon))

        return entries
