"""Zweckverband Abfallwirtschaft Schwalm-Eder-Kreis (zva-sek.de).

Demonstrates: resolving a district -> sub-district -> (optional) street
cascade by scraping a <select> off a yearly calendar page and two
semicolon-separated JS-assignment endpoints, then POSTing the resolved ids to
an ICS-generating servlet. That cascade is the ``prepare`` of a
YearlyRetriever, which already fetches the current year and, from November,
next year too on a best-effort basis, which is exactly what this provider
needs near year-end.

The two JS-assignment endpoints are the shared "abfallkalender" vendor module,
which frankenberg_de runs as well, so reading their replies is
``service/Abfallkalender.py``'s job rather than this source's.
"""

import re
from datetime import datetime
from typing import ClassVar, final

from bs4 import BeautifulSoup, Tag
from waste_collection_schedule import waste_types as wt
from waste_collection_schedule.base_source import BaseSource
from waste_collection_schedule.config_params import district, street, text_field
from waste_collection_schedule.exceptions import SourceArgumentNotFoundWithSuggestions
from waste_collection_schedule.parsers import EachResponse, IcsParser
from waste_collection_schedule.preprocessors import RowRelabel
from waste_collection_schedule.retrievers import YearlyRetriever
from waste_collection_schedule.service import Abfallkalender as abfallkalender
from waste_collection_schedule.transformers import ICSTransformer

_SERVLET = "https://www.zva-sek.de/module/abfallkalender/generate_ical.php"
_MAIN_URL = "https://www.zva-sek.de/online-dienste/abfallkalender-{year}/{file}"
_API_URL = "https://www.zva-sek.de/module/abfallkalender/{file}"

_SUFFIX_RE = re.compile(r"[ ]*am [0-9]+\.[0-9]+\.[0-9]+[ ]*")


def _resolve_ids(source) -> tuple:
    """The district -> sub-district -> (optional) street cascade, run once."""
    session = source.session
    bezirk = source.params["bezirk"]
    ortsteil = source.params["ortsteil"]
    strasse = source.params.get("strasse") or None
    year = datetime.now().year

    r = session.get(_MAIN_URL.format(year=year, file=f"abfallkalender-{year}.html"))
    if r.status_code == 404:  # try last year's URL if this year isn't up yet
        r = session.get(
            _MAIN_URL.format(year=year, file=f"abfallkalender-{year - 1}.html")
        )
    r.raise_for_status()

    soup = BeautifulSoup(r.text, features="html.parser")
    bezirk_select = soup.find("select", {"name": "ak_bezirk"})
    if not isinstance(bezirk_select, Tag):
        raise SourceArgumentNotFoundWithSuggestions("bezirk", bezirk, [])
    bezirk_options = bezirk_select.find_all("option")
    bezirk_id = None
    for option in bezirk_options:
        if option.text.lower() == bezirk.lower():
            bezirk_id = option.get("value")
            break
    if not bezirk_id:
        raise SourceArgumentNotFoundWithSuggestions(
            "bezirk", bezirk, [option.text for option in bezirk_options]
        )

    r = session.get(
        _API_URL.format(file="get_ortsteile.php"), params={"bez_id": bezirk_id}
    )
    r.raise_for_status()
    ortsteil_id = abfallkalender.resolve(r.text, ortsteil, argument="ortsteil")

    street_id = None
    if strasse is not None:
        r = session.get(
            _API_URL.format(file="get_strassen.php"),
            params={"ot_id": ortsteil_id.split("-")[0]},
        )
        r.raise_for_status()
        street_id = abfallkalender.resolve(r.text, strasse, argument="strasse")

    return bezirk_id, ortsteil_id, street_id


def _calendar_for_year(source, year: int, context: tuple):
    """One year's ICS, generated by the servlet from the resolved ids."""
    bezirk_id, ortsteil_id, street_id = context
    args = {
        "year": str(year),
        "ak_bezirk": bezirk_id,
        "ak_ortsteil": ortsteil_id,
        "alle_arten": "",
        "iCalEnde": 6,
        "iCalBeginn": 17,
    }
    if street_id is not None:
        args["ak_strasse"] = street_id
    r = source.session.post(_SERVLET, data=args)
    r.raise_for_status()
    return r


@final
class Source(BaseSource):
    TITLE = "Zweckverband Abfallwirtschaft Schwalm-Eder-Kreis"
    DESCRIPTION = "Source for ZVA (Zweckverband Abfallwirtschaft Schwalm-Eder-Kreis)."
    URL = "https://www.zva-sek.de"
    COUNTRY = "de"
    RAISE_ON_EMPTY = True
    WASTE_TYPES: ClassVar[list] = [
        wt.GENERAL_WASTE,
        wt.HAZARDOUS,
        wt.ORGANIC,
        wt.PAPER,
        wt.RECYCLABLES,
    ]

    TEST_CASES: ClassVar[dict] = {
        "Fritzlar": {
            "bezirk": "Fritzlar",
            "ortsteil": "Fritzlar-kernstadt",
            "strasse": "Ahornweg",
        },
        "Ottrau": {
            "bezirk": "Ottrau",
            "ortsteil": "immichenhain",
            "strasse": "",
        },
        "Knüllwald": {
            "bezirk": "Knüllwald",
            "ortsteil": "Hergetsfeld",
        },
        "Felsberg": {
            "bezirk": "Felsberg",
            "ortsteil": "Felsberg",
        },
        "Guxhagen": {
            "bezirk": "Guxhagen",
            "ortsteil": "Guxhagen",
        },
    }

    PARAMS = (
        text_field("bezirk", "Collection district"),
        district(field="ortsteil"),
        street(field="strasse", optional=True),
    )

    retrieve = YearlyRetriever(
        prepare=_resolve_ids,
        fetch=_calendar_for_year,
        rollover_month=11,
    )

    parse = EachResponse(IcsParser())

    # Every SUMMARY carries the collection date again, as " am 17.07.2026".
    preprocess = RowRelabel(strip=_SUFFIX_RE.pattern)

    transform = ICSTransformer(
        type_value_map={
            "gelbe(r) tonne/sack": wt.RECYCLABLES,
            "restmüll (3-wöchentlich)": wt.GENERAL_WASTE,
            "restmüll 1,1 m³ (wöchentlich)": wt.GENERAL_WASTE,
            "restmüll 1,1 m³ (2-wöchentlich)": wt.GENERAL_WASTE,
            "restmüll 1,1 m³ (3-wöchentlich)": wt.GENERAL_WASTE,
            "restmüll 1,1 m³ (4-wöchentlich)": wt.GENERAL_WASTE,
            "schadstoffsammlung (achtung: nur selbstanlieferung)": wt.HAZARDOUS,
        }
    )
