"""Generate doc/regions/buergerportal_de.yaml from the live Bürgerportal APIs.

One-off registry generator for the buergerportal_de pipeline source
(mampfes/hacs_waste_collection_schedule#7563). Queries each operator's
``OrteMitOrtsteilen`` endpoint live and writes one region entry per
district/subdistrict pair it returns, pre-filling ``operator``/``district``
(and ``subdistrict`` whenever the row carries an Ortsteil).

Run from the repo root:

    python tools/generate_buergerportal_regions.py

This talks to the live, Azure-hosted Bürgerportal APIs and takes a few
minutes for the larger operators (alb_donau, cochem_zell); it is a build-time
tool, not something the source runs.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import requests
import yaml


class _YamlfmtDumper(yaml.SafeDumper):
    """Match the repo's yamlfmt pre-commit hook (mapping=2, sequence=4,
    offset=2): force block sequences to indent even at top level, which
    PyYAML's default dumper does not do on its own.
    """

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "doc" / "regions" / "buergerportal_de.yaml"

HEADERS = {
    "Accept": "application/json, text/plain;q=0.5",
    "Cache-Control": "no-cache",
}

# operator -> (API base URL, website URL for the listing)
OPERATORS: dict[str, tuple[str, str]] = {
    "cochem_zell": (
        "https://buerger-portal-cochemzell.azurewebsites.net/api",
        "https://www.cochem-zell-online.de/",
    ),
    "alb_donau": (
        "https://buerger-portal-albdonaukreisabfallwirtschaft.azurewebsites.net/api",
        "https://www.aw-adk.de/",
    ),
    "biedenkopf": (
        "https://biedenkopfmzv.buergerportal.digital/api",
        "https://mzv-biedenkopf.de/",
    ),
    "bedburg": (
        "https://buerger-portal-bedburg.azurewebsites.net/api",
        "https://www.bedburg.de/",
    ),
    "klevestadt": (
        "https://buerger-portal-klevestadt.azurewebsites.net/api",
        "https://buerger-app-klevestadt.azurewebsites.net/calendar",
    ),
}


def _fetch_orte(api_base: str) -> list[dict]:
    response = requests.get(
        f"{api_base}/OrteMitOrtsteilen", headers=HEADERS, timeout=30
    )
    response.raise_for_status()
    return response.json()["d"]


def _title(district: str, subdistrict: str | None) -> str:
    # A subdistrict named like its district ("Alf, Alf") is a distinct row
    # from the district with no subdistrict ("Alf", null): the two resolve to
    # different street lists, so their titles must differ too.
    if subdistrict:
        return f"{district} ({subdistrict})"
    return district


def build_entries() -> list[dict]:
    entries: list[dict] = []
    total = 0
    for operator, (api_base, url) in OPERATORS.items():
        rows = _fetch_orte(api_base)
        total += len(rows)
        print(f"{operator}: {len(rows)} rows", file=sys.stderr)
        for row in rows:
            district = row["Ortsname"]
            subdistrict = row.get("Ortsteilname")
            entry: dict = {
                "title": _title(district, subdistrict),
                "url": url,
                "operator": operator,
                "district": district,
            }
            # Carry the subdistrict whenever the row has one, even when it
            # repeats the district name: the street lookup filters on
            # ``OrtsteilName``, so null and a same-named Ortsteil return
            # different streets.
            if subdistrict is not None:
                entry["subdistrict"] = subdistrict
            entries.append(entry)
    print(f"total: {total} rows", file=sys.stderr)
    return entries


def main() -> None:
    entries = build_entries()
    header = (
        "---\n"
        "# Provider registry for the buergerportal_de (c-trace Bürgerportal) source.\n"
        "#\n"
        "# Generated by tools/generate_buergerportal_regions.py from the live\n"
        "# OrteMitOrtsteilen endpoint of each operator. Each entry becomes its own\n"
        "# listing in README.md / sources.json, with its params pre-filled, via\n"
        "# regions.from_yaml() in source/buergerportal_de.py. Re-run the generator\n"
        "# to pick up districts a provider has added or removed; do not hand-edit.\n"
    )
    body = yaml.dump(
        entries,
        Dumper=_YamlfmtDumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=150,
    )
    # yamlfmt's offset=2 indents every sequence item, including at the
    # document root, which PyYAML's dumper never does on its own.
    indented_body = textwrap.indent(body, "  ")
    with open(OUTPUT_PATH, "w", encoding="utf-8") as stream:
        stream.write(header)
        stream.write(indented_body)
    print(f"wrote {len(entries)} entries to {OUTPUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
