name: Assign Issue

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Required permission for the action to assign users
    steps:
      - name: Assign Me Action
        uses: takanome-dev/assign-issue-action@v3.1.0
        with:
          github_token: "${{ github.token }}"
