---
name: Validate with hassfest

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
